In [1]:
import os
from cqpes.data import PIPData
from jax import numpy as jnp
from jaxpip.descriptor import PIPDescriptor

In [2]:
SiH4_data = PIPData.from_file(
    xyz_file=os.path.join("data", "SiH4.xyz"),
    E_file=os.path.join("data", "SiH4_CCSD-T.dat"),
)

SiH4_data.set_reference_energy()

print(repr(SiH4_data))

PIPData INFO | SiH4 (length: 84002)
PIPData INFO | E min: -291.450692 Hartree
PIPData INFO | E max: -291.228446 Hartree
PIPData INFO | V min: 0.0000 eV
PIPData INFO | V max: 6.0476 eV


In [3]:
SiH4_xyz = jnp.asarray(SiH4_data[0].xyz)
SiH4_xyz

An NVIDIA GPU may be present on this machine, but a CUDA-enabled jaxlib is not installed. Falling back to cpu.


Array([[ 0.        ,  0.        ,  0.        ],
       [ 1.4737175 ,  0.        ,  0.        ],
       [-0.49123916,  0.6947171 , -1.2032853 ],
       [-0.49123916, -1.3894342 ,  0.        ],
       [-0.49123916,  0.6947171 ,  1.2032853 ]], dtype=float32)

In [4]:
ab4_pip = PIPDescriptor.from_json(
    os.path.join("basis", "MOL_1_4_4.json"),
    alpha=1.0,
)

In [5]:
p, J_p_xyz = ab4_pip(SiH4_xyz, with_grad=True)

In [6]:
p

Array([1.00000000e+00, 5.40742993e-01, 9.16289270e-01, 2.43669152e-02,
       9.74676535e-02, 2.47738481e-01, 2.47738481e-01, 3.14844728e-01,
       4.87338342e-02, 2.09896505e-01, 8.78416002e-03, 2.92805326e-03,
       2.92805326e-03, 2.23271456e-02, 2.23271456e-02, 4.46542911e-02,
       2.23271456e-02, 2.83750184e-02, 1.13500036e-01, 2.83750184e-02,
       4.80814800e-02, 4.39208001e-03, 1.75683182e-02, 2.23271456e-02,
       2.23271456e-02, 5.67500331e-02, 5.67500331e-02, 1.44244447e-01,
       4.39207954e-03, 4.80814800e-02, 1.97915535e-04, 7.91662198e-04,
       6.70735899e-04, 4.02441481e-03, 2.01220741e-03, 4.02441481e-03,
       2.01220741e-03, 6.70735899e-04, 1.02290586e-02, 5.11453068e-03,
       5.11453068e-03, 5.11453068e-03, 2.55726534e-03, 1.02290586e-02,
       1.29998615e-02, 1.29998615e-02, 2.75353412e-03, 1.58332451e-03,
       7.91662198e-04, 7.91662198e-04, 7.91662198e-04, 4.02441481e-03,
       2.01220741e-03, 4.02441481e-03, 2.01220741e-03, 4.02441481e-03,
      

In [7]:
J_p_xyz

Array([[[ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00],
        [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00],
        [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00],
        [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00],
        [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00]],

       [[ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00],
        [-2.2075740e-01,  0.0000000e+00,  0.0000000e+00],
        [ 7.3585801e-02, -1.0406604e-01,  1.8024766e-01],
        [ 7.3585801e-02,  2.0813207e-01,  0.0000000e+00],
        [ 7.3585801e-02, -1.0406604e-01, -1.8024766e-01]],

       [[ 1.4901161e-08, -4.4703484e-08,  0.0000000e+00],
        [-2.2907233e-01,  0.0000000e+00,  0.0000000e+00],
        [ 7.6357432e-02, -1.0798572e-01,  1.8703675e-01],
        [ 7.6357447e-02,  2.1597148e-01,  0.0000000e+00],
        [ 7.6357432e-02, -1.0798572e-01, -1.8703675e-01]],

       ...,

       [[ 3.7252903e-09, -1.1175871e-08,  0.0000000e+00],
        [-3.3042412e-02,  0.0000000e+00,  0.0000000e+