In [1]:
import os
import dpdata
from jax import numpy as jnp
from jaxpip.descriptor import PIPDescriptor

In [2]:
# load CH4.xyz
s = dpdata.System("CH4.xyz", fmt="xyz")
s

Data Summary
Unlabeled System
-------------------
Frame Numbers     : 1
Atom Numbers      : 5
Element List      :
-------------------
C  H
1  4

In [3]:
# show xyz
xyz = jnp.array(s.data["coords"][0])
xyz

Array([[ 0.88680434,  0.        ,  0.62706536],
       [-0.88680434,  0.        ,  0.62706536],
       [ 0.        ,  0.88680434, -0.62706536],
       [ 0.        , -0.88680434, -0.62706536],
       [ 0.        ,  0.        ,  0.        ]], dtype=float32)

In [4]:
# initialize PIP descriptor

a4b_pip = PIPDescriptor.from_json(
    os.path.join("basis", "A4B_4.json"),
    with_grad=True,
)

a4b_pip

>>> PIPDescriptor INFO
>>> Number of atoms: 5
>>> Length of distance and Morse-like vectors: 10
>>> Length of permutation invariant polynomial: 83

In [5]:
# calculate PIP and its Jacobian matrix with respect to xyz
p, J_p_xyz = a4b_pip(xyz)

In [6]:
# show p
p

Array([1.        , 1.350109  , 1.0183166 , 0.68354785, 0.68741924,
       0.08641405, 0.68741924, 0.34565625, 0.45569858, 0.17282811,
       0.15381068, 0.11601135, 0.46404523, 0.1166684 , 0.11601135,
       0.1166684 , 0.23333679, 0.05866456, 0.01955486, 0.1166684 ,
       0.01955486, 0.4614321 , 0.2320227 , 0.2320227 , 0.1166684 ,
       0.02933228, 0.1166684 , 0.11732913, 0.15381068, 0.02933228,
       0.01297882, 0.07831398, 0.03937876, 0.07831398, 0.01968938,
       0.07875752, 0.03937876, 0.03960178, 0.00248913, 0.0066003 ,
       0.03937876, 0.07875752, 0.03960178, 0.01980089, 0.01980089,
       0.00995652, 0.0066003 , 0.15574588, 0.07831398, 0.156628  ,
       0.156628  , 0.03937876, 0.07831398, 0.03937876, 0.07875752,
       0.03937876, 0.01968938, 0.01980089, 0.07875752, 0.01980089,
       0.01968938, 0.03960178, 0.03960178, 0.01991303, 0.03960178,
       0.00995652, 0.00995652, 0.03960178, 0.00995652, 0.07787295,
       0.15574588, 0.07831398, 0.07831398, 0.03937876, 0.00248

In [7]:
# show J_p(xyz)
J_p_xyz

Array([[[ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00],
        [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00],
        [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00],
        [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00],
        [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00]],

       [[-2.7558985e-01,  0.0000000e+00, -1.9487146e-01],
        [ 2.7558985e-01,  0.0000000e+00, -1.9487146e-01],
        [ 0.0000000e+00, -2.7558985e-01,  1.9487146e-01],
        [ 0.0000000e+00,  2.7558985e-01,  1.9487146e-01],
        [ 1.7523334e-09,  1.7523334e-09,  0.0000000e+00]],

       [[-3.3943883e-01, -2.3925475e-09, -2.4001952e-01],
        [ 3.3943883e-01, -2.3925475e-09, -2.4001952e-01],
        [-2.3925475e-09, -3.3943883e-01,  2.4001952e-01],
        [-2.3925475e-09,  3.3943883e-01,  2.4001952e-01],
        [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00]],

       ...,

       [[-2.6550712e-02, -7.0024819e-11, -1.8774189e-02],
        [ 2.6550712e-02, -7.0024819e-11, -1.8774189e-

In [8]:
%%timeit

p, J_p_xyz = a4b_pip(xyz)

142 µs ± 1.21 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
